name: Deploy Development Build

# Trigger on push to "development" branch
on:
  push:
    branches:
      - development
    paths:
      - .github/**
      - files/**
      - Dockerfile

jobs:
  build_deploy_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3.1.0

      - name: Docker login
        run: docker login --username '${{secrets.REGISTRY_USERNAME}}' --password '${{secrets.REGISTRY_ACCESS_TOKEN}}'

      - name: Build + Push image ("development")
        run: |
          docker buildx build \
            --platform "linux/amd64,linux/arm/v7,linux/arm64" \
            --tag "${{secrets.REGISTRY_USERNAME}}/openconnect:development" \
            --output "type=image,push=true" \
            --file ./Dockerfile .
