name: Deploy Release Build

# Trigger on release
on:
  release:
    types:
      - released

jobs:
  build_deploy_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3.1.0

      - name: Docker login
        run: docker login --username '${{secrets.REGISTRY_USERNAME}}' --password '${{secrets.REGISTRY_ACCESS_TOKEN}}'

      - name: Build + Push image (tag = git release tag)
        run: |
          docker buildx build \
            --platform "linux/amd64,linux/arm/v7,linux/arm64" \
            --tag "${{secrets.REGISTRY_USERNAME}}/openconnect:${GITHUB_REF#refs/tags/}" \
            --output "type=image,push=true" \
            --file ./Dockerfile .

      - name: Build + Push image ("latest")
        run: |
          docker buildx build \
            --platform "linux/amd64,linux/arm/v7,linux/arm64" \
            --tag "${{secrets.REGISTRY_USERNAME}}/openconnect:latest" \
            --output "type=image,push=true" \
            --file ./Dockerfile .
